version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: starwars-mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: starwars-db
    volumes:
      - mongodb_data:/data/db
    networks:
      - starwars-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starwars-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - EXTERNAL_API_URL=${EXTERNAL_API_URL}
      - WEB_URL=${WEB_URL}
    volumes:
      - .:/starwars-api
      - /starwars-api/node_modules
    networks:
      - starwars-network
    command: npm run start:dev

  web:
    build:
      context: ../starwars-web
      dockerfile: Dockerfile.dev
    container_name: starwars-web
    restart: always
    ports:
      - '5173:5173'
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:3000
      - NODE_ENV=development
    volumes:
      - ../starwars-web:/starwars-web
      - /starwars-web/node_modules
    networks:
      - starwars-network

volumes:
  mongodb_data:

networks:
  starwars-network:
    driver: bridge
